<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

# Python for Finance (2nd ed.)

**Mastering Data-Driven Finance**

&copy; Dr. Yves J. Hilpisch | The Python Quants GmbH

<img src="http://hilpisch.com/images/py4fi_2nd_shadow.png" width="300px" align="left">

# Object Oriented Programming

## Introduction

In [8]:
class HumanBeing(object):  
    def __init__(self, first_name, eye_color):  
        self.first_name = first_name  
        self.eye_color = eye_color  
        self.position = 0  
    def walk_steps(self, steps):  
        self.position += steps  

In [9]:
Sandra = HumanBeing('Sandra', 'blue')  

In [10]:
Sandra.first_name  

'Sandra'

In [11]:
Sandra.position  

0

In [12]:
Sandra.walk_steps(5)  

In [13]:
Sandra.position  

5

### 多态性

多态性可以呈现出多种形式。在Python环境中特别重要的是所谓的“鸭子类型”（Duck typing）。这个名词指的是标准操作可能在许多不同类上实现，它们的实例并不真正知道所处理对象的事实。对于一个金融工具类，这可能意味着，人们可以调用方法get_current_price（获取当前价格），而无须考虑对象的具体类型（股票、期权、掉期）。

## A Brief Look at Standard Objects

### int

In [14]:
n = 5  

In [15]:
type(n)  

int

In [16]:
n.numerator  

5

In [17]:
n.bit_length()  

3

In [18]:
n + n  

10

In [19]:
2 * n  

10

In [20]:
n.__sizeof__()  

28

### list

In [21]:
l = [1, 2, 3, 4]  

In [22]:
type(l)  

list

In [23]:
l[0]  

1

In [24]:
l.append(10)  

In [25]:
l + l  

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [26]:
2 * l  

[1, 2, 3, 4, 10, 1, 2, 3, 4, 10]

In [27]:
sum(l)  

20

In [28]:
l.__sizeof__()  

104

### ndarray

In [29]:
import numpy as np  

In [30]:
a = np.arange(16).reshape((4, 4))  

In [31]:
a  

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
type(a)  

numpy.ndarray

In [33]:
a.nbytes  

64

In [34]:
a.sum()  

120

In [35]:
a.cumsum(axis=0)  

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36]], dtype=int32)

In [36]:
a + a  

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [37]:
2 * a  

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [38]:
sum(a)  

array([24, 28, 32, 36])

In [39]:
np.sum(a)  

120

In [40]:
a.__sizeof__()  

112

### DataFrame

In [41]:
import pandas as pd  

In [42]:
df = pd.DataFrame(a, columns=list('abcd'))  

In [43]:
type(df)  

pandas.core.frame.DataFrame

In [44]:
df.columns  

Index(['a', 'b', 'c', 'd'], dtype='object')

In [45]:
df.sum()  

a    24
b    28
c    32
d    36
dtype: int64

In [46]:
df.cumsum()  

a   b   c   d
0   0   1   2   3
1   4   6   8  10
2  12  15  18  21
3  24  28  32  36

In [47]:
df + df  

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [48]:
2 * df  

a   b   c   d
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

In [49]:
np.sum(df)  

a    24
b    28
c    32
d    36
dtype: int64

In [50]:
df.__sizeof__()  

192

## Basics of Python Classes

In [51]:
class FinancialInstrument(object):  
    pass  

In [52]:
fi = FinancialInstrument()  

In [53]:
type(fi)  

__main__.FinancialInstrument

In [54]:
fi  

In [55]:
fi.__str__()  

'<__main__.FinancialInstrument object at 0x0000021FC1BD0808>'

In [56]:
fi.price = 100  

In [57]:
fi.price  

100

In [59]:
class FinancialInstrument(object):
    author = 'D M'  
    def __init__(self, symbol, price):  
        self.symbol = symbol  
        self.price = price  

In [60]:
FinancialInstrument.author  

'D M'

In [61]:
aapl = FinancialInstrument('AAPL', 100)  

In [62]:
aapl.symbol  

'AAPL'

In [63]:
aapl.author  

'D M'

In [64]:
aapl.price = 105  

In [65]:
aapl.price  

105

In [66]:
class FinancialInstrument(FinancialInstrument):  
    def get_price(self):  
        return self.price  
    def set_price(self, price):  
        self.price = price  

In [67]:
fi = FinancialInstrument('AAPL', 100)  

In [68]:
fi.get_price()  

100

In [69]:
fi.set_price(105)  

In [70]:
fi.get_price()  

105

In [71]:
fi.price  

105

In [72]:
class FinancialInstrument(object):
    def __init__(self, symbol, price):
        self.symbol = symbol  
        self.__price = price  
    def get_price(self):
        return self.__price
    def set_price(self, price):
        self.__price = price

In [73]:
fi = FinancialInstrument('AAPL', 100)

In [74]:
fi.get_price()  

100

In [75]:
# causes intentional error
fi.__price  

AttributeError: 'FinancialInstrument' object has no attribute '__price'

In [76]:
# 如果在类名前加上一个前导下划线，那么直接访问和操纵仍然是有可能的
# 虽然Python类的封装基本上可以通过实例属性和对应的处理方法实现，但它并不能完全对用户隐藏数据。从这个意义上说，该特性更多的是Python的设计原则，而非Python类的技术特征。

fi._FinancialInstrument__price  

100

In [78]:
fi._FinancialInstrument__price = 105  

In [79]:
fi.get_price()

105

In [81]:
fi.set_price(100)  

In [82]:
fi.get_price()

100

In [83]:
class PortfolioPosition(object):
    def __init__(self, financial_instrument, position_size):
        self.position = financial_instrument  
        self.__position_size = position_size  
    def get_position_size(self):
        return self.__position_size
    def update_position_size(self, position_size):
        self.__position_size = position_size
    def get_position_value(self):
        return self.__position_size * \
               self.position.get_price()  

In [84]:
pp = PortfolioPosition(fi, 10)

In [85]:
pp.get_position_size()

10

In [86]:
pp.get_position_value()  

1000

In [87]:
pp.position.get_price()  

100

In [88]:
pp.position.set_price(105)  

In [89]:
pp.get_position_value()  

1050

## Python Data Model

In [90]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):  
        self.x = x  
        self.y = y  
        self.z = z  

In [91]:
v = Vector(1, 2, 3)  

In [92]:
v  

In [93]:
class Vector(Vector):
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)

In [94]:
v = Vector(1, 2, 3)

In [95]:
v  

Vector(1, 2, 3)

In [96]:
print(v)  

Vector(1, 2, 3)


In [99]:
class Vector(Vector):
    def __abs__(self):
        return (self.x ** 2 +  self.y ** 2 +
                self.z ** 2) ** 0.5  
    
    def __bool__(self):
        return bool(abs(self))

In [100]:
v = Vector(1, 2, -1)  

In [101]:
abs(v)

2.449489742783178

In [102]:
bool(v)

True

In [103]:
v = Vector()  

In [104]:
v  

Vector(0, 0, 0)

In [105]:
abs(v)

0.0

In [106]:
bool(v)

False

In [107]:
class Vector(Vector):
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)  
    
    def __mul__(self, scalar):
        return Vector(self.x * scalar,
                      self.y * scalar,
                      self.z * scalar)  

In [108]:
v = Vector(1, 2, 3)

In [109]:
v + Vector(2, 3, 4)

Vector(3, 5, 7)

In [110]:
v * 2

Vector(2, 4, 6)

In [112]:
class Vector(Vector):
    def __len__(self):
        return 3  
    
    def __getitem__(self, i):
        if i in [0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')

In [113]:
v = Vector(1, 2, 3)

In [114]:
len(v)

3

In [115]:
v[0]

1

In [116]:
v[-2]

2

In [117]:
# causes intentional error
v[3]

IndexError: Index out of range.

In [118]:
class Vector(Vector):
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

In [119]:
v = Vector(1, 2, 3)

In [120]:
for i in range(3):  
    print(v[i])  

1
2
3


In [121]:
for coordinate in v:  
    print(coordinate)  

1
2
3


In [122]:
class Vector(object):
    def __init__(self, x=0, y=0, z=0):
        self.x = x
        self.y = y
        self.z = z
    
    def __repr__(self):
        return 'Vector(%r, %r, %r)' % (self.x, self.y, self.z)
    
    def __abs__(self):
        return (self.x ** 2 +  self.y ** 2 + self.z ** 2) ** 0.5
    
    def __bool__(self):
        return bool(abs(self))
    
    def __add__(self, other):
        x = self.x + other.x
        y = self.y + other.y
        z = self.z + other.z
        return Vector(x, y, z)
    
    def __mul__(self, scalar):
        return Vector(self.x * scalar,
                      self.y * scalar,
                      self.z * scalar)
    
    def __len__(self):
        return 3
    
    def __getitem__(self, i):
        if i in [0, -3]: return self.x
        elif i in [1, -2]: return self.y
        elif i in [2, -1]: return self.z
        else: raise IndexError('Index out of range.')
            
    def __iter__(self):
        for i in range(len(self)):
            yield self[i]

<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

<a href="http://tpq.io" target="_blank">http://tpq.io</a> | <a href="http://twitter.com/dyjh" target="_blank">@dyjh</a> | <a href="mailto:training@tpq.io">training@tpq.io</a>